### ISSUE TITLE
Expose the character habitat_specific in the fullkey

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#239]
The habitat_specific character is not viewable in the simplkey. Clicking on "get more questions" never adds it to the list of questions.

For the fullkey, this character would be a powerful question to reduce the matching set of species. 

How do we expose this to the user in a useful way? How costly would the solution be to implement?
## Method 1

Add the character_group "habitat" to the Get more Questions box. This would add habitat_specific to the list of questions. habitat_general is a default character, and would remain in the the list of questions.
## Method 2

On the working area for habitat_general, include a link labeled "More details..." Clicking this link would replace habitat_general in the filter working area with the habitat_specific.

**Comment by brandon-rhodes** [comment]
I hope that means you decided you like it. :) Hope things are going well, Sid!

**Comment by sidkoul** [comment]
More then like Brandon! It's a useful feature that people use all the time.
