### ISSUE TITLE
Add a Technical Requirements page

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#575]
The About section should include a technical requirements page that lists the minimum browser requirements.

**Comment by sidkoul** [comment]
# OS X notes
Chrome no longer supports Mac OS X 10.5
https://support.google.com/chrome/answer/2599452?hl=en
...you'll be unable to install Chrome on any Mac still running 10.5 (which is an OS X version also no longer being updated by Apple). 

Firefox no longer works with Mac OS X 10.5
https://support.mozilla.org/en-US/kb/firefox-no-longer-works-mac-os-x-10-5
...Firefox 16 is the last version of Firefox that works with Mac OS X 10.5 (Leopard) on an Intel-based Mac.

For reference, as of Jan 30, 2015
- Chrome is at Version 40.0.2214.94
- FireFox is Version 35.0.1

## OS X VERSIONS
Unlike Microsoft, Apple doesn't have a clearly spelled out EOL policy, but in the past have supported n-1 generations of OS X.

OS X 10.4 Tiger, Apr 29, 2005; most recent: 10.4.11, Nov 14, 2007
OS X 10.5 Leopard, Oct 26, 2007; most recent: 10.5.8 (9L31a), Aug 13, 2009
OS X 10.6 Snow Leopard, Aug 28, 2009; most recent: 10.6.8 v1.1, Jul 25, 2011
OS X 10.7 Lion, Jul 20, 2011; most recent: 10.7.5 11G63, Oct 4, 2012
OS X 10.8 Mountain Lion, Jul 25, 2012; most recent: 10.8.5 12F45, Oct 3, 2013
OS X 10.9 Mavericks, Oct 22, 2013; most recent: 10.9.5 13F34, Sep 17, 2014
OS X 10.10 Yosemite, Oct 16, 2014; most recent: 10.10.2 14C109, Jan 27, 2015

- PowerPC was dropped after Mac OS X 10.5 (Leopard)
- Intel only 10.6 (Snow Leopard) and after

## SAFARI WEB BROWSER VERSIONS
Safari 4.1.3 (Nov 18, 2010)
Mac OS X v10.4 Tiger
Supported 2005–2010

Safari 5.0.6 (Jul 20, 2011)
Mac OS X v10.5 Leopard
Supported 2007–2011

Safari 5.1.10 (Sep 12, 2013)
Mac OS X v10.6 Snow Leopard
Supported 2009–2013

Safari 6.1.6 (Aug 13, 2014)
Mac OS X v10.7 Lion
2011-2014

Safari 6.2.3 (Jan 27, 2015)
OS X v10.8 Mountain Lion
Supported since 2012

Safari 7.1.3 (Jan 27, 2015)
OS X v10.9 Mavericks
Supported since 2013

Safari 8.0.3 (Jan 27, 2015)
OS X v10.10 Yosemite
Supported since 2014

https://en.wikipedia.org/wiki/Safari_version_history#Version_compatibility

**Comment by jnga** [comment]
Because only fairly recent versions of browsers are practical for us to test with, the page says that the current and previous versions are supported. This is similar to the supported browsers for Google Apps.
