### ISSUE TITLE
DKey Fig links on Species page don't open in tooltip

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#578]
The dkey contains illustrations that open in a tooltip. These are indicated by the presence of the word "Fig." For example, examine the Fig links here:

https://gobotany.newenglandwild.org/dkey/juncus/

On the species page however, tooltips are not aware of Fig links. For example, examine the bottom of this page and note the Fig link in "1a.  Tepals ascending or appressed to the capsule [Fig. 147]; leaf sheaths..." links to the image, not a tooltip:

https://gobotany.newenglandwild.org/species/juncus/effusus/

Or  [Fig. 355] at the bottom of this page:
https://gobotany.newenglandwild.org/species/sanicula/canadensis/

**Comment by jnga** [comment]
Reopening because the fix is not working with the latest Dev deployment. It works locally with thedev JS files, but not with the production JS file, so it must be something with the latter.
