### ISSUE TITLE
Upgrade to Django 1.8

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#582]
Version 1.8 will be released in April 2015. It's designated a Long–term support (LTS) release, with support (security and data loss fixes) for at least 3 years.
https://docs.djangoproject.com/en/1.8/internals/release-process/#lts-releases

Migrating from South to the native migrations that are built into Django versions 1.7 and after could be a sticking point. See this blog entry for helpful tips:

https://www.twilio.com/blog/2014/10/upgrading-your-django-reusable-app-to-support-django-1-7.html

**Comment by jnga** [comment]
The Django 1.8 upgrade is ready to deploy and test in Dev and Production.
