### ISSUE TITLE
Images on species page not enlargable on Android

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#585]
This went unnoticed until recently. A user visiting a species page using an Android device, isn't able to expand any of the plant images at the top of the page. The thumbnails don't respond to touch.

**Comment by jnga** [comment]
Tested using Device Mode in Chrome, simulating Galaxy S5, Nexus 5X, and Nexus 6P. The images now enlarge as expected. If problems still occur, please reopen and mention the device and browser.

**Comment by sidkoul** [comment]
This bug is back in production for both Android and iOS. Have tested using Google Dev tools and a physical HTC One M8, Android version 6 (Marshmallow).

**Comment by jnga** [comment]
Opened a new issue (#672) for this, so closing #585.
