### ISSUE TITLE
Modify Post a Sighting link under distribution map

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#586]
The link to "post a sighting" currently sends users to the PlantShare login page. This should be changed to point to the PlantShare home page.

Users that don't have a login will get a sense of what PlantShare is and how to create an account, and those that do can simply login.

**Comment by jnga** [comment]
The link now goes to the Post a Sighting page only if logged in, otherwise to the PlantShare main page.

**Comment by jnga** [comment]
Forgot a detail originally intended: now the only way the link takes the user to the PlantShare main page is if they are new to PlantShare.

If they have already registered for PlantShare but are logged out, the link brings up the basic login screen. Upon logging in, they are taken right to the Post a Sighting page.

As before, if they are already logged in, the link just goes to the Post a Sighting page.
