### ISSUE TITLE
Edit Dkey in the admin

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#592]
Add the ability to edit and manipulate dkey data by admins. This includes couplets, species info on the taxon page, figures, and the list of species under each couplet.

**Comment by jnga** [comment]
The ability to edit the D. Key in the Admin is available for testing in Dev. Documentation is in a new section of the README. Prior to Release 2.5, it can be found at: https://github.com/newfs/gobotany-app/tree/592-dkey

**Comment by jnga** [comment]
The D. Key now has basic editing capability in the Admin, which should allow various types of edits and updates. Please feel free to test in Dev and see how this first pass meets current needs. We can make further improvements to handle other situations as needed.
