### ISSUE TITLE
Fix incorrect copyright attribution

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#596]
On the Trapa Natans page
https://gobotany.newenglandwild.org/species/trapa/natans/

This image
http://newfs.s3.amazonaws.com/taxon-images-1000s1000/Lythraceae/trapa-natans-ha-dcameron.jpg

It's attributed to Don Cameron, but should be Jean Baxter with copyright to NEWFS.

It looks like a slide photo, not a digital image.

It's also used here
http://umaine.edu/publications/2535e/

**Comment by jnga** [comment]
Fixed (S3 and the Admin, no code changes).
