### ISSUE TITLE
Admin improvements for the Distributions table

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#598]
The Distribution records table contains presence and nativity data. It powers the maps and the distributions table on the species pages. The admin has requested the following improvements:

- [x] Increase pagination from 100 to 150 rows per page.

- [x] After creating a new record, clicking on "Save and add another" should populate the scientific name with the previous entered name.

- [ ] Add a new button labeled "Save and edit next record" that allows the admin to save the current record, and open the next record to edit.

**Comment by jnga** [comment]
Known limitations for the Save and Edit Next button:
- one can only edit records in sequence on a single (searched/filtered/sorted) page of results at a time
- after the last of that page, a new page needs to be set up before editing a new sequence of records

The latter limitation is the same as how the Save button already works in Django Admin. We could probably fix this one sometime if it would be of help.

Neither limitation should be significant for this feature.
