### ISSUE TITLE
Upgrade to Cedar-14, Cedar-10 is EOL Nov 4, 2015

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#602]
Cedar-10 will reach end-of-life on November 4th, 2015.
Upgrade to Cedar-14 at your earliest convenience.
https://devcenter.heroku.com/articles/cedar-14-migration

_The Cedar-14 stack is the latest version of the Heroku Cedar stack. It features updated system dependencies and runs on a recent version of Ubuntu Linux. In testing, we’ve generally found that apps are faster on Cedar-14 than on Cedar. Some types of apps may consume more memory, however. Please see the Tuning glibc memory behavior article for details._

**Comment by jnga** [comment]
The Cedar-14 upgrade was accomplished along with Release 2.4 (Django 1.8, etc.) in May.
