### ISSUE TITLE
404 error on dkey for genus Coleataenia

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#618]
https://gobotany.newenglandwild.org/genus/coleataenia/
 
Clicking on “Dichotomous Key” yields a 404 Not Found error.

**Comment by jnga** [comment]
Fixed locally and in Dev, partially via Admin edits.

The full fix depends on DKey editing capability (added in Rel. 2.5) and an Admin fix made in this issue. So, this will need to be completed with some Admin edits after Release 2.6 is deployed:

In the Admin, change Sorengia to Coleataenia by searching for 'sorengia' in:

D. Key pages (2 records):
- genus record
- species record (title, and beginning of "text" field)
Figures (1 record)
Leads (1 record)

In the D. Key Pages record for Panicum: in the "text" field, change Sorengia to Coleataenia.

In the (Core) Genus record for Panicum: change Sorengia to Coleataenia.

Then run the DKey sync script as mentioned in the ReadMe.

Finally, rebuild the Solr index as mentioned in the ReadMe.

Note that this fix makes the Coleataenia species image appear at bottom on the DKey Poaceae Group 10 page, where it did not (as Sorengia) before.
