### ISSUE TITLE
Searching for spergularia yields an error

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#619]
Searching for Spergularia or spergularia, yields "An error has occurred" page.

https://gobotany.newenglandwild.org/search/?q=spergularia

<img width="826" alt="spergularia go botany error" src="https://cloud.githubusercontent.com/assets/1482988/9260424/8b8bce12-41d5-11e5-84bb-de7edcd5b74f.png">

**Comment by jnga** [comment]
Closing this issue, a duplicate of #627.
