### ISSUE TITLE
Search results for Solanum sysimbriifolium include an invalid link

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#622]
Search results for (incorrectly spelled) Solanum sysimbriifolium include a link to a non-existing page. E.g.

https://gobotany.newenglandwild.org/search/?q=Solanum+sysimbriifolium

https://gobotany.newenglandwild.org/species/solanum/sysimbriifolium/     [404]
https://gobotany.newenglandwild.org/species/solanum/sisymbriifolium/     [correct]

**Comment by jnga** [comment]
Fixed in Dev. Upon release to Production, we will need to correct the spelling of this plant's search suggestion via the Admin.
