### ISSUE TITLE
Attaching an image to a question yields HTTP 500

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#645]
Attaching an image to an "Ask the Botanist" question fails with an HTTP 500 response. The user is left waiting for the UPLOAD_SPINNER to complete. See screenshot:

![image](https://cloud.githubusercontent.com/assets/1482988/15519664/872d17f0-21d0-11e6-9a6e-a97a3a73e818.png)

The image never gets uploaded to our S3 bucket here:

http://newfs.s3.amazonaws.com/upload_images/question

Note: this URL will result in an access denied error message because directory browsing is turned off.

**Comment by jnga** [comment]
A fix for this image uploads bug is in branch release-2.4.1, ready for deployment to Production. It has been verified in Dev.
