### ISSUE TITLE
First image is repeated on questions with multiple images

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#649]
For "Ask the Botanist" questions with multiple images, the first image is displayed multiple times. Examples: https://gobotany.newenglandwild.org/plantshare/

**Comment by jnga** [comment]
Looking into this. It is also happening for sighting images. It seems to only occur in Production. Even tried putting Release 2.4.1 back into Dev, and it still does not happen there. Will continue investigating.

**Comment by sidkoul** [comment]
I've deployed 2.4.2 but the problem still persists
https://gobotany.newenglandwild.org/plantshare/

**Comment by jnga** [comment]
Verified fixed in Dev.
