### ISSUE TITLE
Dyropteris clintoniana and sometimes confused with section

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#657]
Dyropteris clintoniana should be a clickable link (under the sometimes confused with section) on the Dryopteris cristata page.

https://gobotany.newenglandwild.org/species/dryopteris/cristata/

**Comment by jnga** [comment]
Fixed now in Production. The "sometimes confused with" field for clintonia within the D. cristata taxon record had a typo (Dyr instead of Dry) in its genus name, which caused it to be unlinked on the species page.
