### ISSUE TITLE
Improve styles code

### ISSUE THREAD

**Issue by jnga** [newfs/gobotany-app#658]
Some of the current Sass styles are deeply nested, making maintenance harder and the compiled styles file larger than it could be.

**Comment by sidkoul** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cards do many cool things. Click on this card to open it and learn more...](https://trello.com/c/fqj3jDtp/2-cards-do-many-cool-things-click-on-this-card-to-open-it-and-learn-more)

**Comment by sidkoul** [comment]
Test comment #653
