### ISSUE TITLE
Sign up: CAPTCHA not working

### ISSUE THREAD

**Issue by jnga** [newfs/gobotany-app#688]
On the Sign Up page, the CAPTCHA element says, "reCAPTCHA v1 is shut down" and directs site owners to a web page to upgrade it.

In the Dev environment, the CAPTCHA element says, "An error occurred" followed by a long hex string.

In the local environment, If accessing using 127.0.0.1 or localhost, the "reCAPTCHA v1 is shut down" message appears. Otherwise, "An error occurred" followed by a hex string appears.

**Comment by sidkoul** [comment]
I've created [reCAPTCHA v2](https://www.google.com/recaptcha/admin) public and private keys for our development and production environments. I've updated settings.py accordingly and will send you the keys separately. 

Go Botany Dev Domains

- gobotany-dev.newenglandwild.org
- gobotany-dev.herokuapp.com
- localhost
- 127.0.0.1

Go Botany Production domains

- gobotany.newenglandwild.org
- gobotany-prod.herokuapp.com

**Comment by jnga** [comment]
Tested and verified locally.

**Comment by jnga** [comment]
These changes are also incorporated into the develop branch for the ongoing work on Release 3.0.
