### ISSUE TITLE
Update Google Analytics tracker code

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#751]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-137710767-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-137710767-2');
</script>

**Comment by sidkoul** [comment]
I just verified that the GC-code is the one associated with Go Botany.

![image](https://user-images.githubusercontent.com/1482988/115441313-b536a100-a1de-11eb-9f0b-0ad680f53d31.png)

UA-137710767-2
--

But the stats look weird.
![image](https://user-images.githubusercontent.com/1482988/115441558-fc249680-a1de-11eb-91e4-cee8d73818df.png)

Should we wait another week to look into it?

**Comment by jnga** [comment]
Thanks—that's the new one you provided for us to switch to, so I'm thinking it will be fine. Planning to release within a week or so.
