### ISSUE TITLE
Search results for a species in a genus that only contains a single species

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#786]
Searching for a species that is the only one in a genus results in no results. Examples:

Phellodendron amurense 
https://gobotany.nativeplanttrust.org/search/?q=Phellodendron+amurense
Phellodendron
https://gobotany.nativeplanttrust.org/search/?q=Phellodendron

Microstegium vimineum
https://gobotany.nativeplanttrust.org/search/?q=Microstegium+vimineum
Microstegium
https://gobotany.nativeplanttrust.org/search/?q=Microstegium

**Comment by jnga** [comment]
Clarification: in the above examples, the searches in Production that return no results are for the species: Phellodendron amurense and Microstegium vimineum. The searches for just the genus name, Phellodendron and Microstegium, do return results there. Also, locally I do get results for the species.

**Comment by jnga** [comment]
This appears to now be resolved upon running a Production command (first of three) to update some of the search indexes.
