### ISSUE TITLE
404 when searching for orchid

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#788]
Searching on "orchid" and clicking on the first search result, yields a "404 Not Found" error message.

![image](https://user-images.githubusercontent.com/1482988/161133590-4cae8643-17ea-43bb-b7b8-1d7c8d08d383.png)

**Comment by jnga** [comment]
The URL for this search result is incorrect (https://gobotany.nativeplanttrust.org/simple/orchids-and-related-plants/). The Orchids page in the Simple Key has been at /simple/monocots/ for a very long time. Will check the search index.

**Comment by jnga** [comment]
This fix will also require re-indexing the search indexes.
